### ISSUE TITLE
Test name is not being passed through the API

### ISSUE THREAD

**Issue by stezu** [catdad/grandma#84]
I was looking through the code to try and find out what's happening, and it looks like the name property is not being passed through the various modules correctly.

1. [`lib\run.js`](https://github.com/catdad/grandma/blob/master/lib/run.js#L75) takes an `options.test.name` and passes that straight through to `lib\forkmaster.js`.
2. [`lib\forkmaster.js`](https://github.com/catdad/grandma/blob/master/lib/forkmaster.js#L248-L267) passes options straight through to
3. [`lib\run-mode-rate.js`](https://github.com/catdad/grandma/blob/master/lib/run-mode-rate.js#L33) and [`lib\run-mode-concurrent.js`](https://github.com/catdad/grandma/blob/master/lib/run-mode-concurrent.js#L23) which both expect `options.testname` which obviously doesn't exist since the property is `options.test.name`.

**Comment by catdad** [comment]
I can't remember ever figuring out what to do with the name (it was more of forward thinking), but I guess I did. As far as I can tell, the only thing it's used for is to put on the top of the html report.

Did you actually need the name for anything, or just looking for bugs?

**Comment by stezu** [comment]
I'm making a gulp plugin for grandma and I wanted the name for the reporting step. I'm just being lazy really. I could theoretically get it out of the vinyl file, but if grandma does it for me, that's easier.

**Comment by catdad** [comment]
Interesting. I added the name and published v0.4.2. You can get the name in the JSON report already... I'm sure you knew that.

I am leaving this open for now so I can write a test for it. I'm too lazy right now.

**Comment by stezu** [comment]
The json report name was null, hence the open issue. ;)

**Comment by catdad** [comment]
`null` is a fine name.
